

export const LATITUDE="LATITUDE";
export const LONGITUDE="LONGITUDE";
export const UPDATE_CORDS="UPDATE_CORDS"
export const CITY_NAME="CITY_NAME"
export const ADD_TO_CART="ADD_TO_CART"
export const ADD_RESTR_INFO="ADD_RESTR_INFO"
export const CLEAR_CART="CLEAR_CART"
export const CART_TOTAL="CART_TOTAL"
export const DECREMENT="DECREMENT"
export const INCREMENT="INCREMENT"
export const DELETE_CART_ITEMS="DELETE_CART_ITEMS"